### ISSUE TITLE
Implement a full actionlib interface to the WBC

### ISSUE THREAD

**Issue by Rayman** [Rayman/whole_body_planner#2]
It should work with the new (full actionlib) behavior of the WBC:
- an actionlib handle corresponds to a cartesian motion objective
- it will never succeed, so it's up to the client to cancel

To keep backwards compatibility with the executives, a goal will have to be canceled when a new goal with the same link and frame is received.

## TODO's
- [x] keep a map from `goal link+frame` to `actionlib handle` e6ed5ab0355e6ca9a412d926ffaa3f7be59023f2
- [x] cancel the correct handle when a new goal is received e6ed5ab0355e6ca9a412d926ffaa3f7be59023f2
- [x] implement goal feedback to determine when to continue Rayman/amigo_whole_body_controller#10
- [x] use this feedback to cancel a goal if it's not the last one 7579a5c277a7616d285dcd2c645152d26df2e7b9
- [ ] only use the feedback when it is from the current active goal #3
- [x] find a workaround for actionlib clients having a queue size of 1 https://github.com/Rayman/amigo_whole_body_controller/commit/282ec3df9ddcdeed13eb70e50efee64331f63986
